services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: budgetuser
      POSTGRES_PASSWORD: budgetpass
      POSTGRES_DB: budgetdb
    ports:
      - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
